version: '3.3'

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis-cache
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redisapp:
    image: redisapp:latest
    container_name: redis-api
    ports:
      - "8085:8085"
#    depends_on:
#      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.1.21:5432/hibernate_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  db:
    driver: local